[package]
name = "scylla-prepare-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true


[dependencies]
scylla = "0.14.0"
quote = "1.0.37"
syn = "2.0.87"
proc-macro2 = "1.0.89"
include_dir = {version = "0.7.4", features = ["glob"]}
