[package]
name = "example"
version = "0.0.1"
edition = "2021"

[dependencies]
scylla = "0.14.0"
scylla-prepare-derive ={ path= "../scylla-prepare-derive" }
tokio = {version = "1.41.1", features = ["rt-multi-thread"]}
